# Generated by Django 2.0.4 on 2018-11-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_slug', models.SlugField(blank=True, max_length=255)),
                ('category_name', models.CharField(blank=True, max_length=255)),
                ('category_slug', models.SlugField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=555)),
                ('link', models.TextField()),
                ('img_link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
